dnstw and PCRE foo and Import::Base is neat
 * indent, perltidyrc for easy reference
 * `make clean` runs (the possibly dangerous) `git clean --force -x`
 * reduce Perl test boilerplate code via Import::Base. other test
   related cleanups and standardizations
 * remove sporadic linux feature_test_macros related defines. figure
   that out if porting to linux

 * di,ketchup - replace with shell aliases as only using git
 * ddns - remove these various dynamic DNS shell scripts
 * dnstw - performs dynamic DNS changes (new)
 * logsoc - SSH_ORIGINAL_COMMAND logger wrapper (new)
 * pcre-precompile - mostly pcreprecompile(3) in code form (new)
 * v[46]addr - add -a flag to print both forward and reverse forms.
   also, new or more unit tests
 * validate-rsnapshot - SSH_ORIGINAL_COMMAND verification (new)

diff --git a/misc/mopen b/misc/mopen
--- a/misc/mopen
+++ b/misc/mopen
@@ -1,17 +1,17 @@
 #!/usr/local/bin/sh
 #
-# Opens a PDF, unless already open, in which case the PDF viewer is
-# signalled so the PDF is refreshed from disk. Used to either open or
+# opens a PDF, unless already open, in which case the PDF viewer is
+# signalled so the PDF is refreshed from disk. used to either open or
 # refresh a PDF being worked on with lilypond or TeX regenerating the
-# PDF. (Preview.app on Mac OS X has gone downhill for this use-case from
-# ~10.9 onwards. Progress!)
+# PDF. Preview.app on Mac OS X has gone downhill for this use-case from
+# ~10.9 onwards. progress!
 
 FILE="$1"
 if [ ! -r "$FILE" ]; then
-    PROG_NAME="`basename $0`"
-    echo >&2 "$PROG_NAME: could not read file '$FILE'"
-    echo >&2 "Usage: $PROG_NAME foo.pdf"
-    exit 65
+   PROG_NAME="`basename $0`"
+   echo >&2 "$PROG_NAME: could not read file '$FILE'"
+   echo >&2 "Usage: $PROG_NAME foo.pdf"
+   exit 65
 fi
 
 USER_NAME="`id -un`"
@@ -29,12 +29,12 @@ set +e
 
 trap 'exit 0' USR2
 ps xo pid,user,command | while read pid uc; do
-    if echo "$uc" | egrep -q "^$USER_NAME[[:blank:]]*$PDFREADER.*$FILE"; then
-        kill -HUP "$pid"
-        kill -USR2 "$$"
-        # NOTE potential race condition if code moves on to the exec
-        # before the kill-of-self happens (haven't seen it in practice)
-    fi
+   if echo "$uc" | egrep -q "^$USER_NAME[[:blank:]]*$PDFREADER.*$FILE"; then
+      kill -HUP "$pid"
+      kill -USR2 "$$"
+      # NOTE potential race condition if code moves on to the exec
+      # before the kill-of-self happens (haven't seen it in practice)
+   fi
 done
 
 exec setsid $PDFREADER "$FILE" >"$HOME/var/log/$PDFREADER" 2>&1
diff --git a/misc/yak-ssh b/misc/yak-ssh
--- a/misc/yak-ssh
+++ b/misc/yak-ssh
@@ -13,10 +13,15 @@
 #   printf "$SSH_ORIGINAL_COMMAND\n" >> "$HOME"/tmp/ssh-yak
 #   eval "$SSH_ORIGINAL_COMMAND"
 #
+# and because I keep forgetting these:
+#
+#   SSH_CLIENT="srcip srcport dstport"
+#   SSH_CONNECTION="srcip srcport dstip dstport'
+#
 # NOTE software may already support limited access via ssh e.g. git-shell(1)
 
-YAK_OUTPUT=`mktemp -q "/tmp/yak-ssh.XXXXXXXXXX`" || {
-   echo >&2 "mktemp failed to create /tmp file"
+YAK_OUTPUT=`mktemp -q /tmp/yak-ssh.XXXXXXXXXX` || {
+   printf >&2 "mktemp failed to create /tmp file\n"
    exit 1
 }
 chmod go-r "$YAK_OUTPUT"
@@ -24,8 +29,10 @@ chmod go-r "$YAK_OUTPUT"
    printf "$SSH_ORIGINAL_COMMAND\n\n"
    if [ -t 0 ]; then
       tty
-      printf "\n"
+   else
+      printf "no tty on stdin\n"
    fi
+   printf "\n"
    env
 ) >> "$YAK_OUTPUT"
 
