rework or toss some old tools

diff --git a/misc/yak b/misc/yak
--- a/misc/yak
+++ b/misc/yak
@@ -1,70 +1,28 @@
-#!/usr/local/bin/sh
+#!/bin/sh
 #
-# Unix diagnostic tool that saves various invocation details such as arguments,
-# environment settings, and standard input to a temporary file for debugging.
-# Uses include seeing how and with what settings applications such as the LPRng
-# print spooler or the Procmail mail delivery agent call filters or external
-# scripts. (Which may date this script's origins to a particular era, though it
-# does remain handy for debugging now other things.)
-#
-# Output is saved to a temporary file under /tmp by default.
+# yak - unix diagnostic tool that saves various invocation details to a
+# temporary file for debugging. other options are to use tool like
+# strace or sysdig...
 
-shortname="`basename "$0"`"
-shortname="${shortname:=yak}"
-
-#YAK_OUTPUT=/dev/null
-YAK_OUTPUT=`mktemp -q "/tmp/${shortname}.XXXXXXXXXX"` || {
-  echo >&2 "mktemp failed to create /tmp file"
-  exit 1
+YAK_OUTPUT=`mktemp -q "/tmp/yak.XXXXXXXXXX"` || {
+   echo >&2 "mktemp failed to create /tmp file"
+   exit 1
 }
-
-# in the event env contains anything sensitive (or change the tmp dir path)
 chmod go-r "$YAK_OUTPUT"
-
-#logger -t "$shortname" "saving output to $YAK_OUTPUT"
-
 (
-if [ "$#" -gt 0 ]; then
-  echo ARGS::BEGIN
-  echo "$0"
-  for YAK_ARG in "$@"; do
-    echo "$YAK_ARG"
-  done
-  echo ARGS::END
-else
-  echo ARGS::NONE
-fi
-echo
-
-echo UNIX::BEGIN
-echo "pid=$$"
-
-# NOTE may need to fiddle with this or use other utilities to get the real vs.
-# effective user and group settings
-id
-
-echo UNIX::END
-echo
-
-if test -t 0; then
-  echo TTY::BEGIN
-  tty
-  echo TTY::END
-else
-  echo TTY:NONE
-fi
-echo
-
-echo ENV::BEGIN
-set
-echo ENV::END
-echo
-
-# NOTE this will stall the script on command line waiting for input
-echo STDIN::BEGIN
-cat
-echo STDIN::END
-
+   printf "$0 $@\npid=$$\n"
+   # NOTE may need to fiddle with this or use other utilities to get the
+   # real vs. effective user...
+   id
+   groups
+   printf "\n"
+   tty
+   printf "\n"
+   env
+   printf "\n"
+   if [ -t 0 ]; then
+      printf "istty\n"
+   else
+      cat
+   fi
 ) >> "$YAK_OUTPUT"
-
-exit 0
diff --git a/misc/yak-ssh b/misc/yak-ssh
--- a/misc/yak-ssh
+++ b/misc/yak-ssh
@@ -1,62 +1,34 @@
-#!/usr/local/bin/sh
+#!/bin/sh
 #
-# Like yak, but for SSH_ORIGINAL_COMMAND via SSH sessions so that the
-# exact commands used over SSH sessions can be logged. Actual command is
-# run after this logging. Usage: in ~/.ssh/authorized_keys add a command
-# statement prefixing the SSH key in question:
+# yak-ssh - like yak, but for SSH_ORIGINAL_COMMAND via SSH sessions. in
+# ~/.ssh/authorized_keys add a command restriction for the key
 #
 #   command="/path/to/yak-ssh" ssh-rsa AAAA...
 #
-# Then use SSH, inspect the ssh-yak.* YAK_OUTPUT files for the command and
-# env gleanings. A shorter version less concerned with the env and tmp
-# security needs might run something like:
+# then use SSH and inspect the ssh-yak.* output for the command and env
+# gleanings. a shorter version less concerned with the env and tmp
+# security needs might run something like
 #
 #   #!/bin/sh
-#   echo "$SSH_ORIGINAL_COMMAND" >> "$HOME/tmp/ssh-yak"
+#   printf "$SSH_ORIGINAL_COMMAND\n" >> "$HOME"/tmp/ssh-yak
 #   eval "$SSH_ORIGINAL_COMMAND"
 #
-# Note that software may already support limited access via ssh, e.g.
-# git via git-shell(1).
+# NOTE software may already support limited access via ssh e.g. git-shell(1)
 
-shortname="`basename "$0"`"
-shortname="${shortname:=ssh-yak}"
-
-#YAK_OUTPUT=/dev/null
-YAK_OUTPUT=`mktemp -q "/tmp/${shortname}.XXXXXXXXXX`" || {
-  echo >&2 "mktemp failed to create /tmp file"
-  exit 1
+YAK_OUTPUT=`mktemp -q "/tmp/yak-ssh.XXXXXXXXXX`" || {
+   echo >&2 "mktemp failed to create /tmp file"
+   exit 1
 }
-
-# in the event env contains anything sensitive (or change the tmp dir path)
 chmod go-r "$YAK_OUTPUT"
-
-#logger -i -t "$shortname" "ssh-command is $SSH_ORIGINAL_COMMAND"
-
 (
-echo SSH-COMMAND::BEGIN
-echo "$SSH_ORIGINAL_COMMAND"
-echo SSH-COMMAND::END
-echo
-
-# shouldn't be set, unless perhaps `ssh -t` used for some reason
-if test -t 0; then
-  echo TTY::BEGIN
-  tty
-  echo TTY::END
-else
-  echo TTY:NONE
-fi
-echo
-
-# might instead do env(1) if interested in exported variables vs. what the
-# shell sets
-echo ENV::BEGIN
-set
-echo ENV::END
-echo
-
+   printf "$SSH_ORIGINAL_COMMAND\n\n"
+   if [ -t 0 ]; then
+      tty
+      printf "\n"
+   fi
+   env
 ) >> "$YAK_OUTPUT"
 
-# but need eval not exec to deal with shell quoting and whatnot in the
-# env var...
+# if there's no fancy shell syntax then instead
+#exec $SSH_ORIGINAL_COMMAND
 eval "$SSH_ORIGINAL_COMMAND"
