Better show individual arguments, do not fallback to stupid if mktemp fails.

diff --git a/yak/yak b/yak/yak
--- a/yak/yak
+++ b/yak/yak
@@ -1,28 +1,35 @@
 #!/bin/sh
 #
-# Unix diagnostic tool that saves various invocation details such as
-# arguments, environment settings, and standard input to a temporary
-# file for debugging.  Uses include seeing how and with what settings
-# applications such as the LPRng print spooler or the Procmail mail
-# delivery agent call filters or external scripts.
+# Unix diagnostic tool that saves various invocation details such as arguments,
+# environment settings, and standard input to a temporary file for debugging.
+# Uses include seeing how and with what settings applications such as the LPRng
+# print spooler or the Procmail mail delivery agent call filters or external
+# scripts. (Which may date this script's origins to a particular era, though it
+# does remain handy for debugging now other things.)
 #
 # Output is saved to a temporary file under /tmp by default.
 
 shortname=`basename $0`
 shortname=${shortname:=yak}
 
-#OUTPUT=/dev/null
-OUTPUT=`mktemp -q /tmp/${shortname}.XXXXXXXXXX`
-if [ $? -ne 0 ]; then
-  OUTPUT=/tmp/${shortname}.$$
-fi
+#YAK_OUTPUT=/dev/null
+YAK_OUTPUT=`mktemp -q /tmp/${shortname}.XXXXXXXXXX` || {
+  echo >&2 "mktemp failed to create /tmp file"
+  exit 1
+}
 
-#logger -t $shortname "saving output to $OUTPUT"
+# in the event env contains anything sensitive (or change the tmp dir path)
+chmod go-r $YAK_OUTPUT
+
+#logger -t $shortname "saving output to $YAK_OUTPUT"
 
 (
 if [ $# -gt 0 ]; then
   echo ARGS::BEGIN
-  echo "$0 $@"
+  echo $0
+  for YAK_ARG in "$@"; do
+    echo $YAK_ARG
+  done
   echo ARGS::END
 else
   echo ARGS::NONE
@@ -32,8 +39,8 @@ echo
 echo UNIX::BEGIN
 echo pid=$$
 
-# may need to fiddle with this or use other utilities to get the real
-# vs. effective user and group settings
+# NOTE may need to fiddle with this or use other utilities to get the real vs.
+# effective user and group settings
 id
 
 echo UNIX::END
@@ -53,11 +60,11 @@ set
 echo ENV::END
 echo
 
-# this will stall the script on command line waiting for input
+# NOTE this will stall the script on command line waiting for input
 echo STDIN::BEGIN
 cat
 echo STDIN::END
 
-) >> $OUTPUT
+) >> $YAK_OUTPUT
 
 exit 0
diff --git a/yak/yak-ssh b/yak/yak-ssh
--- a/yak/yak-ssh
+++ b/yak/yak-ssh
@@ -7,7 +7,7 @@
 #
 #   command="/path/to/yak-ssh" ssh-rsa AAAA...
 #
-# Then use SSH, inspect the ssh-yak.* output files for the command and
+# Then use SSH, inspect the ssh-yak.* YAK_OUTPUT files for the command and
 # env gleanings. A shorter version less concerned with the env and tmp
 # security needs might run something like:
 #
@@ -21,11 +21,14 @@
 shortname=`basename $0`
 shortname=${shortname:=ssh-yak}
 
-#OUTPUT=/dev/null
-OUTPUT=`mktemp -q /tmp/${shortname}.XXXXXXXXXX`
-if [ $? -ne 0 ]; then
-  OUTPUT=/tmp/${shortname}.$$
-fi
+#YAK_OUTPUT=/dev/null
+YAK_OUTPUT=`mktemp -q /tmp/${shortname}.XXXXXXXXXX` || {
+  echo >&2 "mktemp failed to create /tmp file"
+  exit 1
+}
+
+# in the event env contains anything sensitive (or change the tmp dir path)
+chmod go-r $YAK_OUTPUT
 
 #logger -i -t $shortname "ssh-command is $SSH_ORIGINAL_COMMAND"
 
@@ -52,7 +55,7 @@ set
 echo ENV::END
 echo
 
-) >> $OUTPUT
+) >> $YAK_OUTPUT
 
 # but need eval not exec to deal with shell quoting and whatnot in the
 # env var...
