Remove yet more bashisms, other shell fixes and improvements.

diff --git a/dns/ddns/create-cname b/dns/ddns/create-cname
--- a/dns/ddns/create-cname
+++ b/dns/ddns/create-cname
@@ -4,7 +4,7 @@
 
 DOM=example.edu
 KEY=/etc/nsuk.key
-TIMEOUT=7
+MAXWAITSECS=7
 
 [ $# -ne 2 ] && {
   echo >&2 "usage: $0 existinghost cname"
@@ -21,6 +21,11 @@ echo $2 | grep $DOM && {
   exit 65
 }
 
+[ -r $KEY ] || {
+  echo >&2 "$0: cannot read nsupdate keyfile $KEY"
+  exit 65
+}
+
 # could do 'yxdomain' but that assumes 'A' or 'AAAA' exists;
 # 'prereq yxrrset' again falls into 'A' vs. 'AAAA' trap, so
 # just make an agnostic DNS lookup...
@@ -29,7 +34,7 @@ host $1.$DOM >/dev/null || {
   exit 68
 }
 
-nsupdate -k $KEY -t $TIMEOUT <<EOF
+nsupdate -k $KEY -t $MAXWAITSECS <<EOF
 prereq nxdomain $2.$DOM
 update add $2.$DOM 3600 CNAME $1.$DOM
 send
diff --git a/dns/ddns/create-host b/dns/ddns/create-host
--- a/dns/ddns/create-host
+++ b/dns/ddns/create-host
@@ -5,7 +5,7 @@
 
 DOM=example.edu
 KEY=/etc/nsuk.key
-TIMEOUT=7
+MAXWAITSECS=7
 
 [ $# -ne 2 ] && {
   echo >&2 "usage: $0 host ipaddr"
@@ -17,7 +17,12 @@ echo $1 | grep $DOM && {
   exit 65
 }
 
-nsupdate -k $KEY -t $TIMEOUT <<EOF
+[ -r $KEY ] || {
+  echo >&2 "$0: cannot read nsupdate keyfile $KEY"
+  exit 65
+}
+
+nsupdate -k $KEY -t $MAXWAITSECS <<EOF
 prereq nxrrset $1.$DOM A
 update add $1.$DOM 86400 A $2
 send
@@ -27,9 +32,9 @@ STATUS=$?
 if [ $STATUS -ne 0 ]; then
   echo >&2 "$0: non-zero exit from nsupdate (A not created)"
 else
-  REV=$( perl -e 'print join ".", reverse split /[.]/, shift' $2 )
+  REV=`perl -e 'print join ".", reverse split /[.]/, shift' $2`
 
-  nsupdate -k $KEY -t $TIMEOUT <<EOF_REV
+  nsupdate -k $KEY -t $MAXWAITSECS <<EOF_REV
 prereq nxrrset $REV.in-addr.arpa. PTR
 update add $REV.in-addr.arpa 86400 PTR $1.$DOM.
 send
diff --git a/dns/ddns/create-reverse b/dns/ddns/create-reverse
--- a/dns/ddns/create-reverse
+++ b/dns/ddns/create-reverse
@@ -5,7 +5,7 @@
 
 DOM=example.edu
 KEY=/etc/nsuk.key
-TIMEOUT=7
+MAXWAITSECS=7
 
 [ $# -ne 2 ] && {
   echo >&2 "usage: $0 host ipaddr"
@@ -17,9 +17,14 @@ echo $1 | grep $DOM && {
   exit 65
 }
 
-REV=$( perl -e 'print join ".", reverse split /[.]/, shift' $2 )
+[ -r $KEY ] || {
+  echo >&2 "$0: cannot read nsupdate keyfile $KEY"
+  exit 65
+}
 
-nsupdate -k $KEY -t $TIMEOUT <<EOF
+REV=`perl -e 'print join ".", reverse split /[.]/, shift' $2`
+
+nsupdate -k $KEY -t $MAXWAITSECS <<EOF
 prereq nxrrset $REV.in-addr.arpa. PTR
 update add $REV.in-addr.arpa 86400 PTR $1.$DOM.
 send
diff --git a/dns/ddns/delete-cname b/dns/ddns/delete-cname
--- a/dns/ddns/delete-cname
+++ b/dns/ddns/delete-cname
@@ -4,7 +4,7 @@
 
 DOM=example.edu
 KEY=/etc/nsuk.key
-TIMEOUT=7
+MAXWAITSECS=7
 
 [ $# -ne 1 ] && {
   echo >&2 "usage: $0 cname"
@@ -16,7 +16,12 @@ echo $1 | grep $DOM && {
   exit 65
 }
 
-nsupdate -k $KEY -t $TIMEOUT <<EOF
+[ -r $KEY ] || {
+  echo >&2 "$0: cannot read nsupdate keyfile $KEY"
+  exit 65
+}
+
+nsupdate -k $KEY -t $MAXWAITSECS <<EOF
 prereq yxrrset $1.$DOM CNAME
 update delete $1.$DOM CNAME
 send
diff --git a/dns/ddns/delete-host b/dns/ddns/delete-host
--- a/dns/ddns/delete-host
+++ b/dns/ddns/delete-host
@@ -4,7 +4,7 @@
 
 DOM=example.edu
 KEY=/etc/nsuk.key
-TIMEOUT=7
+MAXWAITSECS=7
 
 [ $# -lt 1 -o $# -gt 2 ] && {
   echo >&2 "usage: $0 host [ipaddr]"
@@ -16,11 +16,16 @@ echo $1 | grep $DOM && {
   exit 65
 }
 
+[ -r $KEY ] || {
+  echo >&2 "$0: cannot read nsupdate keyfile $KEY"
+  exit 65
+}
+
 IP=
 if [ $# -eq 2 ]; then
   IP=$2
 else
-  for hostip in $(dig +short -t A $1.$DOM); do
+  for hostip in `dig +short -t A $1.$DOM`; do
     [ $IP ] && {
       echo >&2 "$0: multiple A records for '$1', do not know which to delete"
       exit 65
@@ -34,7 +39,7 @@ else
   }
 fi
 
-nsupdate -k $KEY -t $TIMEOUT <<EOF
+nsupdate -k $KEY -t $MAXWAITSECS <<EOF
 prereq yxrrset $1.$DOM A
 update delete $1.$DOM A
 send
@@ -44,9 +49,9 @@ STATUS=$?
 if [ $STATUS -ne 0 ]; then
   echo >&2 "$0: non-zero exit from nsupdate (on delete A)"
 else
-  REV=$( perl -e 'print join ".", reverse split /[.]/, shift' $IP )
+  REV=`perl -e 'print join ".", reverse split /[.]/, shift' $IP`
 
-  nsupdate -k $KEY -t $TIMEOUT <<EOF_REV
+  nsupdate -k $KEY -t $MAXWAITSECS <<EOF_REV
 prereq yxrrset $REV.in-addr.arpa. PTR
 update delete $REV.in-addr.arpa. PTR
 send
diff --git a/dns/ddns/delete-reverse b/dns/ddns/delete-reverse
--- a/dns/ddns/delete-reverse
+++ b/dns/ddns/delete-reverse
@@ -4,16 +4,21 @@
 
 DOM=example.edu
 KEY=/etc/nsuk.key
-TIMEOUT=7
+MAXWAITSECS=7
 
 [ $# -ne 1 ] && {
   echo >&2 "usage: $0 ipaddr"
   exit 64
 }
 
-REV=$( perl -e 'print join ".", reverse split /[.]/, shift' $1 )
+[ -r $KEY ] || {
+  echo >&2 "$0: cannot read nsupdate keyfile $KEY"
+  exit 65
+}
 
-nsupdate -v -d -k $KEY -t $TIMEOUT <<EOF
+REV=`perl -e 'print join ".", reverse split /[.]/, shift' $1`
+
+nsupdate -v -d -k $KEY -t $MAXWAITSECS <<EOF
 prereq yxrrset $REV.in-addr.arpa. PTR
 update delete $REV.in-addr.arpa. PTR
 send
diff --git a/dns/ddns/rename-host b/dns/ddns/rename-host
--- a/dns/ddns/rename-host
+++ b/dns/ddns/rename-host
@@ -5,7 +5,7 @@
 
 DOM=example.edu
 KEY=/etc/nsuk.key
-TIMEOUT=7
+MAXWAITSECS=7
 
 [ $# -ne 2 ] && {
   echo >&2 "usage: $0 oldhost newhost"
@@ -17,8 +17,13 @@ echo $1 $2 | grep $DOM && {
   exit 65
 }
 
+[ -r $KEY ] || {
+  echo >&2 "$0: cannot read nsupdate keyfile $KEY"
+  exit 65
+}
+
 IP=
-for hostip in $(dig +short -t A $1.$DOM); do
+for hostip in `dig +short -t A $1.$DOM`; do
   [ $IP ] && {
     echo >&2 "$0: multiple A records for '$1', do not know which to rename"
     exit 65
@@ -31,7 +36,7 @@ done
   exit 68
 }
 
-nsupdate -k $KEY -t $TIMEOUT <<EOF
+nsupdate -k $KEY -t $MAXWAITSECS <<EOF
 prereq yxrrset $1.$DOM A
 update delete $1.$DOM A
 update add $2.$DOM 86400 A $IP
@@ -42,9 +47,9 @@ STATUS=$?
 if [ $STATUS -ne 0 ]; then
   echo >&2 "$0: non-zero exit from nsupdate (A not renamed)"
 else
-  REV=$( perl -e 'print join ".", reverse split /[.]/, shift' $IP )
+  REV=`perl -e 'print join ".", reverse split /[.]/, shift' $IP`
 
-  nsupdate -k $KEY -t $TIMEOUT <<EOF_REV
+  nsupdate -k $KEY -t $MAXWAITSECS <<EOF_REV
 prereq yxrrset $REV.in-addr.arpa. PTR
 update delete $REV.in-addr.arpa. PTR
 update add $REV.in-addr.arpa 86400 PTR $2.$DOM.
diff --git a/filesys/fling b/filesys/fling
--- a/filesys/fling
+++ b/filesys/fling
@@ -9,12 +9,14 @@
 # The author disclaims all copyrights and releases this script into the
 # public domain.
 
-if [ -z $FTARGET ]; then
-  echo "error: must specify FTARGET env. variable as target directory" >&2
-fi
-
 if [ -z $1 ]; then
   echo "usage: `basename $0` file [file2 ...]" >&2
+  exit 64
+fi
+
+if [ -z $FTARGET ]; then
+  echo "error: must specify FTARGET env. variable as target directory" >&2
+  exit 65
 fi
 
 copyto -m "$@" $FTARGET >/dev/null
diff --git a/filesys/ndir b/filesys/ndir
--- a/filesys/ndir
+++ b/filesys/ndir
@@ -48,30 +48,30 @@ for f in "$@"; do
       continue
     fi
 
-    if [ ! -e $part ]; then
-      mkdir -- $part
+    if [ ! -d "$part" ]; then
+      mkdir -- "$part"
       if [ $? -ne 0 ]; then
-        echo "error: could not create $part of $f" >&2
+        echo "error: could not create '$part' of $f" >&2
         exit 1
       fi
     elif [ -d $part ]; then
       # fall through to CVS tests below
       :
     else
-      echo "error: $part of $f not a directory" >&2
+      echo "error: '$part' of '$f' not a directory" >&2
       exit 1
     fi
 
     # add dir to CVS automagically if CVS available
     if [ -f CVS/Root -a ! -f "$part/CVS/Root" ]; then
       if test $VERBOSE = yes ; then
-        echo "notice: adding $part to CVS" >&2
+        echo "notice: adding '$part' to CVS" >&2
       fi
-      cvs add -- $part >/dev/null
+      cvs add -- "$part" >/dev/null
       STATUS=$?
       if [ $STATUS -ne 0 ]; then
         IFS=$OLDIFS
-        echo "error: could not add $part of $f to CVS" >&2
+        echo "error: could not add '$part' of '$f' to CVS" >&2
         exit $STATUS
       fi
     fi
@@ -81,22 +81,22 @@ for f in "$@"; do
     # in-subversion-and-new directory to save on svn calls
     if [ -f .svn/entries -a ! -f "$part/.svn/entries" ]; then
       if test $VERBOSE = yes ; then
-        echo "notice: adding $part to subversion" >&2
+        echo "notice: adding '$part' to subversion" >&2
       fi
-      svn add -- $part >/dev/null
+      svn add -- "$part" >/dev/null
       STATUS=$?
       if [ $STATUS -ne 0 ]; then
         IFS=$OLDIFS
-        echo "error: could not add $part of $f to Subversion" >&2
+        echo "error: could not add '$part' of '$f' to Subversion" >&2
         exit $STATUS
       fi
     fi
 
-    cd -- $part
+    cd -- "$part"
     STATUS=$?
     if [ $STATUS -ne 0 ]; then
       IFS=$OLDIFS
-      echo "error: could not chdir to $part of $f" >&2
+      echo "error: could not chdir to '$part' of '$f'" >&2
       exit $STATUS
     fi
   done
diff --git a/vcs_wrappers/orig b/vcs_wrappers/orig
--- a/vcs_wrappers/orig
+++ b/vcs_wrappers/orig
@@ -6,17 +6,24 @@
 # The author disclaims all copyrights and releases this script into
 # the public domain.
 
+STATUS=0
+
 for f in "$@"; do
-  if [ ! -e $f ]; then
-    echo "warning: no such file: $f" >&2
+  if [ ! -r $f ]; then
+    echo "warning: cannot read file: $f" >&2
+    STATUS=1
   elif [ -f $f ]; then
     cp -p -f $f $f.orig
     RETURN=$?
     if [ $RETURN -ne 0 ]; then
       echo "warning: non-zero exit from cp: $RETURN" >&2
+      STATUS=1
     fi
 # TODO write handlers for directories, Mac OS X HFS+ infested files?
   else
     echo "warning: no handle method for: $f" >&2
+    STATUS=1
   fi
 done
+
+exit $STATUS
