Refurbish the DDNS scripts.

diff --git a/dns/ddns/create-cname b/dns/ddns/create-cname
--- a/dns/ddns/create-cname
+++ b/dns/ddns/create-cname
@@ -1,48 +1,59 @@
 #!/bin/sh
 #
 # Create a CNAME.
+#
+# NOTE there must exist some record for the target of the CNAME, though
+# this could be a MX or TXT or some other not-A or not-AAAA record.
+# There does not appear to be any way to specify that either an A or an
+# AAAA must exist; the alternative would be a race-condition prone
+# lookup for the said types hopefully against a master DNS server...
 
-DOM=example.edu
+DOM=example.net
 KEY=/etc/nsuk.key
+DNS_TTL=3593
+
+# e.g. for testing, or if running local to the master DNS server anyways;
+# otherwise perhaps better to let nsupdate figure out where the request
+# needs to go.
+SERVER=127.0.0.1
+
 MAXWAITSECS=7
+PROG_NAME=`basename $0`
 
 [ $# -ne 2 ] && {
-  echo >&2 "usage: $0 existinghost cname"
+  echo >&2 "usage: $PROG_NAME existinghost cname"
   exit 64
 }
 
-echo $1 | grep $DOM && {
-  echo >&2 "$0: use short host names"
+echo $1 | fgrep $DOM >/dev/null && {
+  echo >&2 "$PROG_NAME: use short host name"
   exit 65
 }
 
-echo $2 | grep $DOM && {
-  echo >&2 "$0: use short host names"
+echo $2 | fgrep $DOM >/dev/null && {
+  echo >&2 "$PROG_NAME: use short host name"
   exit 65
 }
 
 [ -r $KEY ] || {
-  echo >&2 "$0: cannot read nsupdate keyfile $KEY"
+  echo >&2 "$PROG_NAME: cannot read nsupdate keyfile $KEY"
   exit 65
 }
 
-# could do 'yxdomain' but that assumes 'A' or 'AAAA' exists;
-# 'prereq yxrrset' again falls into 'A' vs. 'AAAA' trap, so
-# just make an agnostic DNS lookup...
-host $1.$DOM >/dev/null || {
-  echo >&2 "$0: existinghost does not resolve"
-  exit 68
-}
-
-nsupdate -k $KEY -t $MAXWAITSECS <<EOF
-prereq nxdomain $2.$DOM
-update add $2.$DOM 3600 CNAME $1.$DOM
+(
+  if [ ! -z $SERVER ]; then
+    echo server $SERVER
+  fi
+  cat <<EOF
+prereq yxdomain $1.$DOM.
+prereq nxdomain $2.$DOM.
+update add $2.$DOM. $DNS_TTL CNAME $1.$DOM.
 send
 EOF
+) | nsupdate -k $KEY -t $MAXWAITSECS
 
 STATUS=$?
 if [ $STATUS -ne 0 ]; then
-  echo >&2 "$0: non-zero exit from nsupdate"
+  echo "$PROG_NAME: failed to update add $2.$DOM. $DNS_TTL CNAME $1.$DOM."
 fi
-
 exit $STATUS
diff --git a/dns/ddns/create-host b/dns/ddns/create-host
--- a/dns/ddns/create-host
+++ b/dns/ddns/create-host
@@ -1,49 +1,95 @@
 #!/bin/sh
 #
-# Create A host (and PTR if possible). (Reverse ownership might be tricky
-# to figure out, or cross ownership boundaries...)
+# Create A (or AAAA) host (and PTR if possible). Reverse ownership might
+# be tricky to figure out. This is why this script creates the reverse
+# in a subsequent step, and does not rollback the forward record if the
+# reverse creation fails. (Business logic to check what the NS are and
+# then to vary the action taken depending on those results would greatly
+# complicate this code, so...)
 
-DOM=example.edu
+DOM=example.net
 KEY=/etc/nsuk.key
-MAXWAITSECS=7
+DNS_TTL=3593
 
-[ $# -ne 2 ] && {
-  echo >&2 "usage: $0 host ipaddr"
+# e.g. for testing, or if running local to the master DNS server anyways;
+# otherwise perhaps better to let nsupdate figure out where the request
+# needs to go.
+SERVER=127.0.0.1
+
+MAXWAITSECS=7
+PROG_NAME=`basename $0`
+
+[ $# -lt 2 ] && {
+  echo >&2 "Usage: $PROG_NAME host ipaddress [ipaddr2 ..]"
   exit 64
 }
 
-echo $1 | grep $DOM && {
-  echo >&2 "$0: use short host names"
+HOST=$1
+shift
+
+echo $HOST | fgrep $DOM >/dev/null && {
+  echo >&2 "$PROG_NAME: use short host name"
   exit 65
 }
 
 [ -r $KEY ] || {
-  echo >&2 "$0: cannot read nsupdate keyfile $KEY"
+  echo >&2 "$PROG_NAME: cannot read nsupdate keyfile $KEY"
   exit 65
 }
 
-nsupdate -k $KEY -t $MAXWAITSECS <<EOF
-prereq nxrrset $1.$DOM A
-update add $1.$DOM 86400 A $2
+for arg in "$@"; do
+  IP=`v4addr -q $arg`
+  DNS_TYPE=A
+  REV_PROG=v4addr
+  if [ -z $IP ]; then
+    IP=`v6addr -q $arg`
+    if [ -z $IP ]; then
+      echo >&2 "$PROG_NAME: could not parse v4 or v6 address from $arg"
+      exit 65
+    fi
+    DNS_TYPE=AAAA
+    REV_PROG=v6addr
+  fi
+
+  (
+    if [ ! -z $SERVER ]; then
+      echo server $SERVER
+    fi
+    # NOTE there used to be a 'prereq nxrrset $HOST.$DOM $DNS_TYPE'
+    # limit here, though one could have a host with multiple A records,
+    # so that limitation was removed.
+    cat <<EOF
+update add $HOST.$DOM $DNS_TTL $DNS_TYPE $arg
 send
 EOF
-
-STATUS=$?
-if [ $STATUS -ne 0 ]; then
-  echo >&2 "$0: non-zero exit from nsupdate (A not created)"
-else
-  REV=`perl -e 'print join ".", reverse split /[.]/, shift' $2`
-
-  nsupdate -k $KEY -t $MAXWAITSECS <<EOF_REV
-prereq nxrrset $REV.in-addr.arpa. PTR
-update add $REV.in-addr.arpa 86400 PTR $1.$DOM.
-send
-EOF_REV
+  ) | nsupdate -k $KEY -t $MAXWAITSECS
 
   STATUS=$?
   if [ $STATUS -ne 0 ]; then
-    echo >&2 "$0: non-zero exit from nsupdate (PTR not created)"
+    echo "$PROG_NAME: failed to update add $HOST.$DOM $DNS_TTL $DNS_TYPE $arg"
+    exit $STATUS
   fi
-fi
 
-exit $STATUS
+  REV=`$REV_PROG -q -r $arg`
+  if [ -z $REV ]; then
+    echo >&2 "$PROG_NAME: $REV_PROG failed to parse reverse address from $arg"
+    exit 65
+  fi
+
+  (
+    if [ ! -z $SERVER ]; then
+      echo server $SERVER
+    fi
+    cat <<EOR
+prereq nxrrset $REV PTR
+update add $REV $DNS_TTL PTR $HOST.$DOM.
+send
+EOR
+  ) | nsupdate -k $KEY -t $MAXWAITSECS
+
+  STATUS=$?
+  if [ $STATUS -ne 0 ]; then
+    echo "$PROG_NAME: failed to update add $REV $DNS_TTL PTR $HOST.$DOM."
+    exit $STATUS
+  fi
+done
diff --git a/dns/ddns/create-mx b/dns/ddns/create-mx
--- a/dns/ddns/create-mx
+++ b/dns/ddns/create-mx
@@ -1,32 +1,53 @@
 #!/bin/sh
 #
-# Create a MX record.
+# Create a MX record. NOTE that some DNS servers (and moreover certain
+# Mail Transport Agents) are rather picky about what MX point to, e.g.
+# if a CNAME is improperly made the target of a MX record.
+#
+# This script requires that some other record exists for both the host
+# the MX is being added for, e.g. an A record, and that the MX target
+# has some sort of record for it. `create-host` can be used to satisfy
+# these requirements.
 
-DOM=example.edu
+DOM=example.net
 KEY=/etc/nsuk.key
+DNS_TTL=3593
+
+# e.g. for testing, or if running local to the master DNS server anyways;
+# otherwise perhaps better to let nsupdate figure out where the request
+# needs to go.
+SERVER=127.0.0.1
+
 MAXWAITSECS=7
+PROG_NAME=`basename $0`
 
 [ $# -ne 2 -a $# -ne 3 ] && {
-  echo >&2 "usage: $0 host mxhost.dom. [priority]"
-  exit 1 
+  echo >&2 "Usage: $PROG_NAME host mxhost.dom [priority]"
+  exit 64
 }
 
-echo $1 | grep $DOM && {
-  echo >&2 "$0: use short host name"
-  exit 1
+echo $1 | fgrep $DOM >/dev/null && {
+  echo >&2 "$PROG_NAME: use short host name"
+  exit 65
 }
 
 PRIORITY=0
 [ $# -eq 3 ] && PRIORITY=$3
 
-nsupdate -k $KEY -t $MAXWAITSECS <<EOF
-update add $1.$DOM 86400 MX $PRIORITY $2
+(
+  if [ ! -z $SERVER ]; then
+    echo server $SERVER
+  fi
+  cat <<EOF
+prereq yxdomain $1.$DOM.
+prereq yxdomain $2.
+update add $1.$DOM. $DNS_TTL MX $PRIORITY $2.
 send
 EOF
+) | nsupdate -k $KEY -t $MAXWAITSECS
 
 STATUS=$?
 if [ $STATUS -ne 0 ]; then
-  echo >&2 "$0: non-zero exit from nsupdate (MX not created)"
+  echo "$PROG_NAME: failed to update add $1.$DOM. $DNS_TTL MX $PRIORITY $2."
 fi
-
 exit $STATUS
diff --git a/dns/ddns/delete-host b/dns/ddns/delete-host
--- a/dns/ddns/delete-host
+++ b/dns/ddns/delete-host
@@ -1,66 +1,83 @@
 #!/bin/sh
 #
-# Deletes A host (and possible associated PTR).
+# Deletes *all* records for a host, and possibly associated PTR records,
+# if IP addresses are also supplied. Will *not* delete hosts that have
+# an associated NS record, to help avoid accidental NS accidents.
 
-DOM=example.edu
+DOM=example.net
 KEY=/etc/nsuk.key
-MAXWAITSECS=7
+DNS_TTL=3593
 
-[ $# -lt 1 -o $# -gt 2 ] && {
-  echo >&2 "usage: $0 host [ipaddr]"
+# e.g. for testing, or if running local to the master DNS server anyways;
+# otherwise perhaps better to let nsupdate figure out where the request
+# needs to go.
+SERVER=127.0.0.1
+
+MAXWAITSECS=7
+PROG_NAME=`basename $0`
+
+[ $# -eq 0 ] && {
+  echo >&2 "usage: $PROG_NAME host [ipaddress ..]"
   exit 64
 }
 
-echo $1 | grep $DOM && {
-  echo >&2 "$0: use short host names"
+HOST=$1
+shift
+
+echo $HOST | fgrep $DOM >/dev/null && {
+  echo >&2 "$PROG_NAME: use short host name"
   exit 65
 }
 
 [ -r $KEY ] || {
-  echo >&2 "$0: cannot read nsupdate keyfile $KEY"
+  echo >&2 "$PROG_NAME: cannot read nsupdate keyfile $KEY"
   exit 65
 }
 
-IP=
-if [ $# -eq 2 ]; then
-  IP=$2
-else
-  for hostip in `dig +short -t A $1.$DOM`; do
-    [ $IP ] && {
-      echo >&2 "$0: multiple A records for '$1', do not know which to delete"
-      exit 65
-    }
-    IP=$hostip
-  done
-
-  [ -z $IP ] && {
-    echo >&2 "$0: no A record found for '$1'"
-    exit 68
-  }
-fi
-
-nsupdate -k $KEY -t $MAXWAITSECS <<EOF
-prereq yxrrset $1.$DOM A
-update delete $1.$DOM A
+(
+  if [ ! -z $SERVER ]; then
+    echo server $SERVER
+  fi
+  cat <<EOF
+prereq yxdomain $HOST.$DOM
+prereq nxrrset $HOST.$DOM NS
+update delete $HOST.$DOM
 send
 EOF
+) | nsupdate -k $KEY -t $MAXWAITSECS
 
 STATUS=$?
 if [ $STATUS -ne 0 ]; then
-  echo >&2 "$0: non-zero exit from nsupdate (on delete A)"
-else
-  REV=`perl -e 'print join ".", reverse split /[.]/, shift' $IP`
+  echo "$PROG_NAME: non-zero exit from nsupdate (on delete A)"
+  exit $STATUS
+fi
 
-  nsupdate -k $KEY -t $MAXWAITSECS <<EOF_REV
-prereq yxrrset $REV.in-addr.arpa. PTR
-update delete $REV.in-addr.arpa. PTR
+# Need to support eviction of multiple IP as expect hosts to have both A
+# and AAAA associated with them.
+for ip in "$@"; do
+  REV=`v4addr -q -r $ip`
+  if [ -z $REV ]; then
+    REV=`v6addr -q -r $ip`
+    if [ -z $REV ]; then
+      echo >&2 "$PROG_NAME: could not parse v4 or v6 address from $ip"
+      exit 65
+    fi
+  fi
+
+  (
+    if [ ! -z $SERVER ]; then
+      echo server $SERVER
+    fi
+    cat <<EOR
+prereq yxrrset $REV PTR
+update delete $REV PTR
 send
-EOF_REV
+EOR
+  ) | nsupdate -k $KEY -t $MAXWAITSECS
 
   STATUS=$?
   if [ $STATUS -ne 0 ]; then
-    echo >&2 "$0: non-zero exit from nsupdate (on delete PTR)"
+    echo "$PROG_NAME: failed to update delete $REV PTR"
+    exit $STATUS
   fi
-fi
-
-exit $STATUS
+done
diff --git a/dns/ddns/delete-mx b/dns/ddns/delete-mx
--- a/dns/ddns/delete-mx
+++ b/dns/ddns/delete-mx
@@ -1,30 +1,76 @@
 #!/bin/sh
 #
-# Deletes all MX records for a host
+# Deletes MX records for a host, all of them if none are specified. When
+# specifying MX, both the priority and the fully qualified MX hostname
+# must be supplied.
 
-DOM=example.edu
+DOM=example.net
 KEY=/etc/nsuk.key
-MAXWAITSECS=7
+DNS_TTL=3593
 
-[ $# -lt 1 -o $# -gt 2 ] && {
-  echo >&2 "usage: $0 host  (deletes all MX)"
+# e.g. for testing, or if running local to the master DNS server anyways;
+# otherwise perhaps better to let nsupdate figure out where the request
+# needs to go.
+SERVER=127.0.0.1
+
+MAXWAITSECS=7
+PROG_NAME=`basename $0`
+
+[ $# -eq 0 ] && {
+  echo >&2 "usage: $PROG_NAME host [0 mx1.dom. [10 mx2.dom. ..]]"
   exit 64
 }
 
-echo $1 | grep $DOM && {
-  echo >&2 "$0: use short host names"
+HOST=$1
+shift
+
+echo $HOST | fgrep $DOM >/dev/null && {
+  echo >&2 "$PROG_NAME: use short host name"
   exit 65
 }
 
-nsupdate -k $KEY -t $MAXWAITSECS <<EOF
-prereq yxrrset $1.$DOM MX
-update delete $1.$DOM MX
+if [ $# -eq 0 ]; then
+  (
+    if [ ! -z $SERVER ]; then
+      echo server $SERVER
+    fi
+    cat <<EOF
+prereq yxrrset $HOST.$DOM. MX
+update delete $HOST.$DOM. MX
 send
 EOF
+  ) | nsupdate -k $KEY -t $MAXWAITSECS
 
-STATUS=$?
-if [ $STATUS -ne 0 ]; then
-  echo >&2 "$0: non-zero exit from nsupdate (on delete MX)"
+  STATUS=$?
+  if [ $STATUS -ne 0 ]; then
+    echo "$PROG_NAME: failed to delete $HOST.$DOM. MX"
+  fi
+  exit $STATUS
 fi
 
-exit $STATUS
+if [ `expr $# % 2` -ne 0 ]; then
+  echo >&2 "$PROG_NAME: priorities and mx must come in pairs"
+  exit 65
+fi
+
+while [ $# -gt 0 ]; do
+  PRI=$1
+  MXH=$2
+  shift 2
+  (
+    if [ ! -z $SERVER ]; then
+      echo server $SERVER
+    fi
+    cat <<EOM
+prereq yxrrset $HOST.$DOM. MX $PRI $MXH
+update delete $HOST.$DOM. MX $PRI $MXH
+send
+EOM
+  ) | nsupdate -k $KEY -t $MAXWAITSECS
+
+  STATUS=$?
+  if [ $STATUS -ne 0 ]; then
+    echo "$PROG_NAME: failed to delete $HOST.$DOM. MX $PRI $MXH"
+    exit $STATUS
+  fi
+done
diff --git a/dns/ddns/delete-ptr b/dns/ddns/delete-ptr
--- a/dns/ddns/delete-ptr
+++ b/dns/ddns/delete-ptr
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# Deletes a CNAME.
+# Deletes PTR for a given ip address.
 
 DOM=example.net
 KEY=/etc/nsuk.key
@@ -15,13 +15,8 @@ MAXWAITSECS=7
 PROG_NAME=`basename $0`
 
 [ $# -ne 1 ] && {
-  echo >&2 "usage: $PROG_NAME cname"
+  echo >&2 "usage: $PROG_NAME ipaddr"
   exit 64
-}
-
-echo $1 | fgrep $DOM >/dev/null && {
-  echo >&2 "$PROG_NAME: use short host name"
-  exit 65
 }
 
 [ -r $KEY ] || {
@@ -29,19 +24,28 @@ echo $1 | fgrep $DOM >/dev/null && {
   exit 65
 }
 
+REV=`v4addr -q -r $1`
+if [ -z $REV ]; then
+  REV=`v6addr -q -r $1`
+  if [ -z $REV ]; then
+    echo >&2 "$PROG_NAME: could not parse v4 or v6 address from $1"
+    exit 65
+  fi
+fi
+
 (
   if [ ! -z $SERVER ]; then
     echo server $SERVER
   fi
   cat <<EOF
-prereq yxrrset $1.$DOM. CNAME
-update delete $1.$DOM. CNAME
+prereq yxrrset $REV PTR
+update delete $REV PTR
 send
 EOF
 ) | nsupdate -k $KEY -t $MAXWAITSECS
 
 STATUS=$?
 if [ $STATUS -ne 0 ]; then
-  echo "$PROG_NAME: failed to update delete $1.$DOM. CNAME"
+  echo "$PROG_NAME: failed to delete $REV PTR"
 fi
 exit $STATUS
diff --git a/dns/ddns/repoint-cname b/dns/ddns/repoint-cname
--- a/dns/ddns/repoint-cname
+++ b/dns/ddns/repoint-cname
@@ -1,44 +1,49 @@
 #!/bin/sh
 #
-# Updates a CNAME.
+# Updates a CNAME to point to a new host.
 
-DOM=example.edu
+DOM=example.net
 KEY=/etc/nsuk.key
+DNS_TTL=3593
+
+# e.g. for testing, or if running local to the master DNS server anyways;
+# otherwise perhaps better to let nsupdate figure out where the request
+# needs to go.
+SERVER=127.0.0.1
+
 MAXWAITSECS=7
+PROG_NAME=`basename $0`
 
 [ $# -ne 2 ] && {
-  echo >&2 "usage: $0 existinghost cname"
+  echo >&2 "usage: $PROG_NAME existinghost cname"
   exit 64
 }
 
-echo $1 $2 | grep $DOM && {
-  echo >&2 "$0: use short host names"
+echo $1 $2 | fgrep $DOM >/dev/null && {
+  echo >&2 "$PROG_NAME: use short host name"
   exit 65
 }
 
 [ -r $KEY ] || {
-  echo >&2 "$0: cannot read nsupdate keyfile $KEY"
+  echo >&2 "$PROG_NAME: cannot read nsupdate keyfile $KEY"
   exit 65
 }
 
-# could do 'yxdomain' but that assumes 'A' or 'AAAA' exists;
-# 'prereq yxrrset' again falls into 'A' vs. 'AAAA' trap, so
-# just make an agnostic DNS lookup...
-host $1.$DOM >/dev/null || {
-  echo >&2 "$0: existinghost does not resolve"
-  exit 68
-}
-
-nsupdate -k $KEY -t $MAXWAITSECS <<EOF
-prereq yxrrset $2.$DOM CNAME
-update delete $2.$DOM CNAME
-update add $2.$DOM 3600 CNAME $1.$DOM
+(
+  if [ ! -z $SERVER ]; then
+    echo server $SERVER
+  fi
+  cat <<EOF
+prereq yxrrset $2.$DOM. CNAME
+prereq yxdomain $1.$DOM.
+update delete $2.$DOM. CNAME
+update add $2.$DOM. $DNS_TTL CNAME $1.$DOM.
 send
 EOF
+) | nsupdate -k $KEY -t $MAXWAITSECS
 
 STATUS=$?
 if [ $STATUS -ne 0 ]; then
-  echo >&2 "$0: non-zero exit from nsupdate"
+  echo "$PROG_NAME: failed to add $2.$DOM. $DNS_TTL CNAME $1.$DOM."
 fi
-
 exit $STATUS
