Use sysexits.h codes, other tweaks.

diff --git a/dns/ddns/create-reverse b/dns/ddns/create-reverse
--- a/dns/ddns/create-reverse
+++ b/dns/ddns/create-reverse
@@ -9,12 +9,12 @@ TIMEOUT=7
 
 [ $# -ne 2 ] && {
   echo >&2 "usage: $0 host ipaddr"
-  exit 1 
+  exit 64
 }
 
 echo $1 | grep $DOM && {
   echo >&2 "$0: use short host names"
-  exit 1
+  exit 65
 }
 
 REV=$( perl -e 'print join ".", reverse split /[.]/, shift' $2 )
@@ -27,7 +27,7 @@ EOF
 
 STATUS=$?
 if [ $STATUS -ne 0 ]; then
-  echo >&2 "$0: could not update reverse record"
+  echo >&2 "$0: could not update PTR"
 fi
 
 exit $STATUS
